name: Build AWS Lambda Ruby images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '30 6 * * MON-FRI'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  ruby-dev-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [aws-lambda-ruby-dev, aws-lambda-ruby-postgres]
        ruby: [2.7, 3.2]
    name: Build ci/${{ matrix.image }}:${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: hashFiles(format('ci/{0}/{1}/get-dependencies.sh', matrix.image, matrix.ruby)) != ''
        with:
          role-to-assume: ${{ vars.LINUX_LAYER_ROLE_ARN }}
          role-duration-seconds: 1800
          aws-region: eu-west-1
      - name: Get image dependencies
        run: ./get-dependencies.sh
        if: hashFiles(format('ci/{0}/{1}/get-dependencies.sh', matrix.image, matrix.ruby)) != ''
        working-directory: ci/${{ matrix.image }}/${{ matrix.ruby }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: ci/${{ matrix.image }}/${{ matrix.ruby }}
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository }}/ci/${{ matrix.image }}:${{ matrix.ruby }}
  ruby-local-images:
    runs-on: ubuntu-latest
    needs: ruby-dev-images
    strategy:
      fail-fast: false
      matrix:
        image: [aws-lambda-ruby-dev, aws-lambda-ruby-postgres]
        ruby: [2.7, 3.2]
    name: Build local-dev/${{ matrix.image }}:${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: local-dev/${{ matrix.image }}/${{ matrix.ruby }}
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository }}/local-dev/${{ matrix.image }}:${{ matrix.ruby }}
